<?php

// autogenerated: Wed, 10 Sep 2014 18:08:53 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Query;


class QueryManager implements \PHPCR\Query\QueryManagerInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Query\QueryManagerInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

    /**
     * {@inheritDoc}
     */
    public function createQuery($statement, $language)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->createQuery($statement, $language));
    }

    /**
     * {@inheritDoc}
     */
    public function getQOMFactory()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getQOMFactory());
    }

    /**
     * {@inheritDoc}
     */
    public function getQuery($node)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getQuery($node));
    }

    /**
     * {@inheritDoc}
     */
    public function getSupportedQueryLanguages()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getSupportedQueryLanguages());
    }

}