<?php

// autogenerated: Wed, 10 Sep 2014 13:41:17 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Query;


class Query implements \PHPCR\Query\QueryInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Query\QueryInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->cancel());
    }

    /**
     * {@inheritDoc}
     */
    public function getBindVariableNames()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getBindVariableNames());
    }

    /**
     * {@inheritDoc}
     */
    public function setLimit($limit)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setLimit($limit));
    }

    /**
     * {@inheritDoc}
     */
    public function setOffset($offset)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setOffset($offset));
    }

    /**
     * {@inheritDoc}
     */
    public function getStatement()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getStatement());
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguage()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getLanguage());
    }

    /**
     * {@inheritDoc}
     */
    public function getStoredQueryPath()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getStoredQueryPath());
    }

    /**
     * {@inheritDoc}
     */
    public function storeAsNode($absPath)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->storeAsNode($absPath));
    }

}