<?php

// autogenerated: Wed, 10 Sep 2014 18:08:53 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Query;


class QueryResult implements \IteratorAggregate, \PHPCR\Query\QueryResultInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Query\QueryResultInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

    /**
     * {@inheritDoc}
     */
    public function getColumnNames()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getColumnNames());
    }

    /**
     * {@inheritDoc}
     */
    public function getRows()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getRows());
    }

    /**
     * {@inheritDoc}
     */
    public function getNodes($prefetch = false)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getNodes($prefetch));
    }

    /**
     * {@inheritDoc}
     */
    public function getSelectorNames()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getSelectorNames());
    }

    public function getIterator()
    {
        throw new \Exception("Iterators not supported on decorated objects (yet)");
    }

}