<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Query

class QueryResult implements \PHPCR\Query\QueryResultInterface
{
    /**
     * {@inheritDoc}
     */
    public function getColumnNames()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getColumnNames())
    }

    /**
     * {@inheritDoc}
     */
    public function getRows()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getRows())
    }

    /**
     * {@inheritDoc}
     */
    public function getNodes($prefetch = false)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getNodes($prefetch))
    }

    /**
     * {@inheritDoc}
     */
    public function getSelectorNames()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getSelectorNames())
    }

}