<?php

// autogenerated: Wed, 10 Sep 2014 13:41:17 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Query;


class Row implements \PHPCR\Query\RowInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Query\RowInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getNode($selectorName));
    }

    /**
     * {@inheritDoc}
     */
    public function getPath($selectorName = null)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getPath($selectorName));
    }

    /**
     * {@inheritDoc}
     */
    public function getScore($selectorName = null)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getScore($selectorName));
    }

}