<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Query

class Row implements \PHPCR\Query\RowInterface
{
    /**
     * {@inheritDoc}
     */
    public function getValues()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getValues())
    }

    /**
     * {@inheritDoc}
     */
    public function getValue($columnName)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getValue($columnName))
    }

    /**
     * {@inheritDoc}
     */
    public function getNode($selectorName = null)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getNode($selectorName))
    }

    /**
     * {@inheritDoc}
     */
    public function getPath($selectorName = null)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getPath($selectorName))
    }

    /**
     * {@inheritDoc}
     */
    public function getScore($selectorName = null)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getScore($selectorName))
    }

}