<?php

// autogenerated: Wed, 10 Sep 2014 18:08:53 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Query;


class Row implements \IteratorAggregate, \PHPCR\Query\RowInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Query\RowInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

    /**
     * {@inheritDoc}
     */
    public function getValues()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getValues());
    }

    /**
     * {@inheritDoc}
     */
    public function getValue($columnName)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getValue($columnName));
    }

    /**
     * {@inheritDoc}
     */
    public function getNode($selectorName = NULL)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getNode($selectorName));
    }

    /**
     * {@inheritDoc}
     */
    public function getPath($selectorName = NULL)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getPath($selectorName));
    }

    /**
     * {@inheritDoc}
     */
    public function getScore($selectorName = NULL)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getScore($selectorName));
    }

    public function getIterator()
    {
        throw new \Exception("Iterators not supported on decorated objects (yet)");
    }

}