<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Retention

class Hold implements \PHPCR\Retention\HoldInterface
{
    /**
     * {@inheritDoc}
     */
    public function isDeep()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isDeep())
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getName())
    }

}