<?php

// autogenerated: Wed, 10 Sep 2014 18:08:53 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Retention;


class RetentionManager implements \PHPCR\Retention\RetentionManagerInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Retention\RetentionManagerInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

    /**
     * {@inheritDoc}
     */
    public function getHolds($absPath)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getHolds($absPath));
    }

    /**
     * {@inheritDoc}
     */
    public function addHold($absPath, $name, $isDeep)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->addHold($absPath, $name, $isDeep));
    }

    /**
     * {@inheritDoc}
     */
    public function removeHold($absPath, \PHPCR\Retention\HoldInterface$hold)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->removeHold($absPath, $hold));
    }

    /**
     * {@inheritDoc}
     */
    public function getRetentionPolicy($absPath)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getRetentionPolicy($absPath));
    }

    /**
     * {@inheritDoc}
     */
    public function setRetentionPolicy($absPath, \PHPCR\Retention\RetentionPolicyInterface$retentionPolicy)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->setRetentionPolicy($absPath, $retentionPolicy));
    }

    /**
     * {@inheritDoc}
     */
    public function removeRetentionPolicy($absPath)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->removeRetentionPolicy($absPath));
    }

}