<?php

// autogenerated: Wed, 10 Sep 2014 13:41:17 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Retention;

use PHPCR\Retention\HoldInterface;
use PHPCR\Retention\RetentionPolicyInterface;

class RetentionManager implements \PHPCR\Retention\RetentionManagerInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Retention\RetentionManagerInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }


    /**
     * {@inheritDoc}
     */
    public function getRetentionPolicy($absPath)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getRetentionPolicy($absPath));
    }

    /**
     * {@inheritDoc}
     */
    public function setRetentionPolicy($absPath, RetentionPolicyInterface $retentionPolicy)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setRetentionPolicy($absPath $retentionPolicy));
    }

    /**
     * {@inheritDoc}
     */
    public function removeRetentionPolicy($absPath)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->removeRetentionPolicy($absPath));
    }

}