<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Lock

class Lock implements \PHPCR\Lock\LockInterface
{
    /**
     * {@inheritDoc}
     */
    public function getLockOwner()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getLockOwner())
    }

    /**
     * {@inheritDoc}
     */
    public function isDeep()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isDeep())
    }

    /**
     * {@inheritDoc}
     */
    public function getNode()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getNode())
    }

    /**
     * {@inheritDoc}
     */
    public function getLockToken()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getLockToken())
    }

    /**
     * {@inheritDoc}
     */
    public function getSecondsRemaining()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getSecondsRemaining())
    }

    /**
     * {@inheritDoc}
     */
    public function isLive()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isLive())
    }

    /**
     * {@inheritDoc}
     */
    public function isSessionScoped()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isSessionScoped())
    }

    /**
     * {@inheritDoc}
     */
    public function isLockOwningSession()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isLockOwningSession())
    }

    /**
     * {@inheritDoc}
     */
    public function refresh()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->refresh())
    }

}