<?php

// autogenerated: Wed, 10 Sep 2014 18:08:53 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Lock;


class LockInfo implements \PHPCR\Lock\LockInfoInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Lock\LockInfoInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDeep($isDeep)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->setIsDeep($isDeep));
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDeep()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getIsDeep());
    }

    /**
     * {@inheritDoc}
     */
    public function setIsSessionScoped($isSessionScoped)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->setIsSessionScoped($isSessionScoped));
    }

    /**
     * {@inheritDoc}
     */
    public function getIsSessionScoped()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getIsSessionScoped());
    }

    /**
     * {@inheritDoc}
     */
    public function setTimeoutHint($timeoutHint)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->setTimeoutHint($timeoutHint));
    }

    /**
     * {@inheritDoc}
     */
    public function getTimeoutHint()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getTimeoutHint());
    }

    /**
     * {@inheritDoc}
     */
    public function setOwnerInfo($ownerInfo)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->setOwnerInfo($ownerInfo));
    }

    /**
     * {@inheritDoc}
     */
    public function getOwnerInfo()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getOwnerInfo());
    }

}