<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Lock

class LockInfo implements \PHPCR\Lock\LockInfoInterface
{
    /**
     * {@inheritDoc}
     */
    public function setIsDeep($isDeep)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setIsDeep($isDeep))
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDeep()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getIsDeep())
    }

    /**
     * {@inheritDoc}
     */
    public function setIsSessionScoped($isSessionScoped)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setIsSessionScoped($isSessionScoped))
    }

    /**
     * {@inheritDoc}
     */
    public function getIsSessionScoped()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getIsSessionScoped())
    }

    /**
     * {@inheritDoc}
     */
    public function setTimeoutHint($timeoutHint)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setTimeoutHint($timeoutHint))
    }

    /**
     * {@inheritDoc}
     */
    public function getTimeoutHint()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getTimeoutHint())
    }

    /**
     * {@inheritDoc}
     */
    public function setOwnerInfo($ownerInfo)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setOwnerInfo($ownerInfo))
    }

    /**
     * {@inheritDoc}
     */
    public function getOwnerInfo()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getOwnerInfo())
    }

}