<?php

// autogenerated: Wed, 10 Sep 2014 13:41:17 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Lock;


class LockInfo implements \PHPCR\Lock\LockInfoInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Lock\LockInfoInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setIsSessionScoped($isSessionScoped));
    }

    /**
     * {@inheritDoc}
     */
    public function getIsSessionScoped()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getIsSessionScoped());
    }

    /**
     * {@inheritDoc}
     */
    public function setTimeoutHint($timeoutHint)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setTimeoutHint($timeoutHint));
    }

    /**
     * {@inheritDoc}
     */
    public function getTimeoutHint()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getTimeoutHint());
    }

    /**
     * {@inheritDoc}
     */
    public function setOwnerInfo($ownerInfo)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setOwnerInfo($ownerInfo));
    }

    /**
     * {@inheritDoc}
     */
    public function getOwnerInfo()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getOwnerInfo());
    }

}