<?php

// autogenerated: Wed, 10 Sep 2014 13:41:16 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Transaction;


class UserTransaction implements \PHPCR\Transaction\UserTransactionInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Transaction\UserTransactionInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->inTransaction());
    }

    /**
     * {@inheritDoc}
     */
    public function rollback()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->rollback());
    }

    /**
     * {@inheritDoc}
     */
    public function setTransactionTimeout($seconds = 0)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setTransactionTimeout($seconds));
    }

}