<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Transaction

class UserTransaction implements \PHPCR\Transaction\UserTransactionInterface
{
    /**
     * {@inheritDoc}
     */
    public function begin()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->begin())
    }

    /**
     * {@inheritDoc}
     */
    public function commit()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->commit())
    }

    /**
     * {@inheritDoc}
     */
    public function inTransaction()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->inTransaction())
    }

    /**
     * {@inheritDoc}
     */
    public function rollback()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->rollback())
    }

    /**
     * {@inheritDoc}
     */
    public function setTransactionTimeout($seconds = 0)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setTransactionTimeout($seconds))
    }

}