<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Security

class AccessControlEntry implements \PHPCR\Security\AccessControlEntryInterface
{
    /**
     * {@inheritDoc}
     */
    public function getPrincipal()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getPrincipal())
    }

    /**
     * {@inheritDoc}
     */
    public function getPrivileges()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getPrivileges())
    }

}