<?php

// autogenerated: Wed, 10 Sep 2014 18:08:53 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Security;


class AccessControlEntry implements \IteratorAggregate, \PHPCR\Security\AccessControlEntryInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Security\AccessControlEntryInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

    /**
     * {@inheritDoc}
     */
    public function getPrincipal()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getPrincipal());
    }

    /**
     * {@inheritDoc}
     */
    public function getPrivileges()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getPrivileges());
    }

    public function getIterator()
    {
        throw new \Exception("Iterators not supported on decorated objects (yet)");
    }

}