<?php

// autogenerated: Wed, 10 Sep 2014 18:08:53 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Security;


class AccessControlList implements \IteratorAggregate, \PHPCR\Security\AccessControlListInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Security\AccessControlListInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

    /**
     * {@inheritDoc}
     */
    public function getAccessControlEntries()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getAccessControlEntries());
    }

    /**
     * {@inheritDoc}
     */
    public function addAccessControlEntry(\PHPCR\Security\PrincipalInterface$principal, array $privileges)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->addAccessControlEntry($principal, $privileges));
    }

    /**
     * {@inheritDoc}
     */
    public function removeAccessControlEntry(\PHPCR\Security\AccessControlEntryInterface$ace)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->removeAccessControlEntry($ace));
    }

    public function getIterator()
    {
        throw new \Exception("Iterators not supported on decorated objects (yet)");
    }

}