<?php

// autogenerated: Wed, 10 Sep 2014 18:08:53 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Security;


class AccessControlManager implements \PHPCR\Security\AccessControlManagerInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Security\AccessControlManagerInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

    /**
     * {@inheritDoc}
     */
    public function getSupportedPrivileges($absPath = NULL)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getSupportedPrivileges($absPath));
    }

    /**
     * {@inheritDoc}
     */
    public function privilegeFromName($privilegeName)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->privilegeFromName($privilegeName));
    }

    /**
     * {@inheritDoc}
     */
    public function hasPrivileges($absPath, array $privileges)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->hasPrivileges($absPath, $privileges));
    }

    /**
     * {@inheritDoc}
     */
    public function getPrivileges($absPath = NULL)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getPrivileges($absPath));
    }

    /**
     * {@inheritDoc}
     */
    public function getPolicies($absPath)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getPolicies($absPath));
    }

    /**
     * {@inheritDoc}
     */
    public function getEffectivePolicies($absPath)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getEffectivePolicies($absPath));
    }

    /**
     * {@inheritDoc}
     */
    public function getApplicablePolicies($absPath)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getApplicablePolicies($absPath));
    }

    /**
     * {@inheritDoc}
     */
    public function setPolicy($absPath, \PHPCR\Security\AccessControlPolicyInterface$policy)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->setPolicy($absPath, $policy));
    }

    /**
     * {@inheritDoc}
     */
    public function removePolicy($absPath, \PHPCR\Security\AccessControlPolicyInterface$policy)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->removePolicy($absPath, $policy));
    }

}