<?php

// autogenerated: Wed, 10 Sep 2014 13:41:17 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Security;


class AccessControlEntry implements \PHPCR\Security\AccessControlEntryInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Security\AccessControlEntryInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

}