<?php

// autogenerated: Wed, 10 Sep 2014 18:08:53 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Security;


class Principal implements \PHPCR\Security\PrincipalInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Security\PrincipalInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

    /**
     * {@inheritDoc}
     */
    public function equals($object)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->equals($object));
    }

    /**
     * {@inheritDoc}
     */
    public function hashCode()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->hashCode());
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getName());
    }

}