<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Security

class Privilege implements \PHPCR\Security\PrivilegeInterface
{
    /**
     * {@inheritDoc}
     */
    public function getName()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getName())
    }

    /**
     * {@inheritDoc}
     */
    public function isAbstract()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isAbstract())
    }

    /**
     * {@inheritDoc}
     */
    public function isAggregate()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isAggregate())
    }

    /**
     * {@inheritDoc}
     */
    public function getDeclaredAggregatePrivileges()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDeclaredAggregatePrivileges())
    }

    /**
     * {@inheritDoc}
     */
    public function getAggregatePrivileges()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getAggregatePrivileges())
    }

}