<?php

// autogenerated: Wed, 10 Sep 2014 13:41:17 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Security;


class Privilege implements \PHPCR\Security\PrivilegeInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Security\PrivilegeInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isAggregate());
    }

    /**
     * {@inheritDoc}
     */
    public function getDeclaredAggregatePrivileges()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDeclaredAggregatePrivileges());
    }

    /**
     * {@inheritDoc}
     */
    public function getAggregatePrivileges()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getAggregatePrivileges());
    }

}