<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR

class ItemVisitor implements \PHPCR\ItemVisitorInterface
{
    /**
     * {@inheritDoc}
     */
    public function visit(ItemInterface $item)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->visit($item))
    }

}