<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR

class Item implements \PHPCR\ItemInterface
{
    /**
     * {@inheritDoc}
     */
    public function getPath()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getPath())
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getName())
    }

    /**
     * {@inheritDoc}
     */
    public function getAncestor($depth)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getAncestor($depth))
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getParent())
    }

    /**
     * {@inheritDoc}
     */
    public function getDepth()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDepth())
    }

    /**
     * {@inheritDoc}
     */
    public function getSession()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getSession())
    }

    /**
     * {@inheritDoc}
     */
    public function isNode()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isNode())
    }

    /**
     * {@inheritDoc}
     */
    public function isNew()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isNew())
    }

    /**
     * {@inheritDoc}
     */
    public function isModified()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isModified())
    }

    /**
     * {@inheritDoc}
     */
    public function isSame(ItemInterface $otherItem)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isSame($otherItem))
    }

    /**
     * {@inheritDoc}
     */
    public function accept(ItemVisitorInterface $visitor)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->accept($visitor))
    }

    /**
     * {@inheritDoc}
     */
    public function revert()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->revert())
    }

    /**
     * {@inheritDoc}
     */
    public function remove()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->remove())
    }

}