<?php

// autogenerated: Wed, 10 Sep 2014 18:08:53 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR;


class Item implements \PHPCR\ItemInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\ItemInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

    /**
     * {@inheritDoc}
     */
    public function getPath()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getPath());
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getName());
    }

    /**
     * {@inheritDoc}
     */
    public function getAncestor($depth)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getAncestor($depth));
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getParent());
    }

    /**
     * {@inheritDoc}
     */
    public function getDepth()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getDepth());
    }

    /**
     * {@inheritDoc}
     */
    public function getSession()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getSession());
    }

    /**
     * {@inheritDoc}
     */
    public function isNode()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->isNode());
    }

    /**
     * {@inheritDoc}
     */
    public function isNew()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->isNew());
    }

    /**
     * {@inheritDoc}
     */
    public function isModified()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->isModified());
    }

    /**
     * {@inheritDoc}
     */
    public function isSame(\PHPCR\ItemInterface$otherItem)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->isSame($otherItem));
    }

    /**
     * {@inheritDoc}
     */
    public function accept(\PHPCR\ItemVisitorInterface$visitor)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->accept($visitor));
    }

    /**
     * {@inheritDoc}
     */
    public function revert()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->revert());
    }

    /**
     * {@inheritDoc}
     */
    public function remove()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->remove());
    }

}