<?php

// autogenerated: Wed, 10 Sep 2014 13:41:17 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR;


class NamespaceRegistry implements \PHPCR\NamespaceRegistryInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\NamespaceRegistryInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getNamespaces());
    }

    /**
     * {@inheritDoc}
     */
    public function getPrefixes()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getPrefixes());
    }

    /**
     * {@inheritDoc}
     */
    public function getURIs()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getURIs());
    }

    /**
     * {@inheritDoc}
     */
    public function getURI($prefix)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getURI($prefix));
    }

    /**
     * {@inheritDoc}
     */
    public function getPrefix($uri)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getPrefix($uri));
    }

}