<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR

class NamespaceRegistry implements \PHPCR\NamespaceRegistryInterface
{
    /**
     * {@inheritDoc}
     */
    public function registerNamespace($prefix, $uri)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->registerNamespace($prefix $uri))
    }

    /**
     * {@inheritDoc}
     */
    public function unregisterNamespaceByURI($uri)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->unregisterNamespaceByURI($uri))
    }

    /**
     * {@inheritDoc}
     */
    public function getNamespaces()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getNamespaces())
    }

    /**
     * {@inheritDoc}
     */
    public function getPrefixes()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getPrefixes())
    }

    /**
     * {@inheritDoc}
     */
    public function getURIs()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getURIs())
    }

    /**
     * {@inheritDoc}
     */
    public function getURI($prefix)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getURI($prefix))
    }

    /**
     * {@inheritDoc}
     */
    public function getPrefix($uri)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getPrefix($uri))
    }

}