<?php

// autogenerated: Wed, 10 Sep 2014 13:41:16 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR;

use PHPCR\ItemInterface;
use PHPCR\ItemVisitorInterface;

class Property implements \PHPCR\PropertyInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\PropertyInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }


    /**
     * {@inheritDoc}
     */
    public function getString()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getString());
    }

    /**
     * {@inheritDoc}
     */
    public function getBinary()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getBinary());
    }

    /**
     * {@inheritDoc}
     */
    public function getLong()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getLong());
    }

    /**
     * {@inheritDoc}
     */
    public function getDouble()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDouble());
    }

    /**
     * {@inheritDoc}
     */
    public function getDecimal()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDecimal());
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDate());
    }

    /**
     * {@inheritDoc}
     */
    public function getBoolean()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getBoolean());
    }

    /**
     * {@inheritDoc}
     */
    public function getNode()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getNode());
    }

    /**
     * {@inheritDoc}
     */
    public function getProperty()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getProperty());
    }

    /**
     * {@inheritDoc}
     */
    public function getLength()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getLength());
    }

    /**
     * {@inheritDoc}
     */
    public function getDefinition()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDefinition());
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getType());
    }

    /**
     * {@inheritDoc}
     */
    public function isMultiple()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isMultiple());
    }

    /**
     * {@inheritDoc}
     */
    public function getPath()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getPath());
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getName());
    }

    /**
     * {@inheritDoc}
     */
    public function getAncestor($depth)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getAncestor($depth));
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getParent());
    }

    /**
     * {@inheritDoc}
     */
    public function getDepth()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDepth());
    }

    /**
     * {@inheritDoc}
     */
    public function getSession()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getSession());
    }

    /**
     * {@inheritDoc}
     */
    public function isNode()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isNode());
    }

    /**
     * {@inheritDoc}
     */
    public function isNew()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isNew());
    }

    /**
     * {@inheritDoc}
     */
    public function isModified()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isModified());
    }

    /**
     * {@inheritDoc}
     */
    public function isSame(ItemInterface $otherItem)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isSame($otherItem));
    }

    /**
     * {@inheritDoc}
     */
    public function accept(ItemVisitorInterface $visitor)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->accept($visitor));
    }

    /**
     * {@inheritDoc}
     */
    public function revert()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->revert());
    }

    /**
     * {@inheritDoc}
     */
    public function remove()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->remove());
    }

}