<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR

class Repository implements \PHPCR\RepositoryInterface
{
    /**
     * {@inheritDoc}
     */
    public function login(CredentialsInterface $credentials = null, $workspaceName = null)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->login($credentials $workspaceName))
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptorKeys()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDescriptorKeys())
    }

    /**
     * {@inheritDoc}
     */
    public function isStandardDescriptor($key)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isStandardDescriptor($key))
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptor($key)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDescriptor($key))
    }

}