<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR

class RepositoryFactory implements \PHPCR\RepositoryFactoryInterface
{
    /**
     * {@inheritDoc}
     */
    public function getRepository(array $parameters = null)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getRepository($parameters))
    }

    /**
     * {@inheritDoc}
     */
    public function getConfigurationKeys()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getConfigurationKeys())
    }

}