<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR

class RepositoryManager implements \PHPCR\RepositoryManagerInterface
{
    /**
     * {@inheritDoc}
     */
    public function getWorkspace()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getWorkspace())
    }

    /**
     * {@inheritDoc}
     */
    public function closeRepository($closeSessionsImmediately)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->closeRepository($closeSessionsImmediately))
    }

}