<?php

// autogenerated: Wed, 10 Sep 2014 18:08:53 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR;


class RepositoryFactory implements \PHPCR\RepositoryFactoryInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\RepositoryFactoryInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

    /**
     * {@inheritDoc}
     */
    public function getRepository(array $parameters = NULL)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getRepository($parameters));
    }

    /**
     * {@inheritDoc}
     */
    public function getConfigurationKeys()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getConfigurationKeys());
    }

}