<?php

// autogenerated: Wed, 10 Sep 2014 18:08:53 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR;


class Repository implements \PHPCR\RepositoryInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\RepositoryInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

    /**
     * {@inheritDoc}
     */
    public function login(\PHPCR\CredentialsInterface$credentials = NULL, $workspaceName = NULL)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->login($credentials, $workspaceName));
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptorKeys()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getDescriptorKeys());
    }

    /**
     * {@inheritDoc}
     */
    public function isStandardDescriptor($key)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->isStandardDescriptor($key));
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptor($key)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getDescriptor($key));
    }

}