<?php

// autogenerated: Wed, 10 Sep 2014 18:08:53 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR;


class RepositoryManager implements \PHPCR\RepositoryManagerInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\RepositoryManagerInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkspace()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getWorkspace());
    }

    /**
     * {@inheritDoc}
     */
    public function closeRepository($closeSessionsImmediately)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->closeRepository($closeSessionsImmediately));
    }

}