<?php

// autogenerated: Wed, 10 Sep 2014 18:08:53 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Observation;


class EventJournal implements \PHPCR\Observation\EventJournalInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Observation\EventJournalInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

    /**
     * {@inheritDoc}
     */
    public function skipTo($date)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->skipTo($date));
    }

    /**
     * {@inheritDoc}
     */
    public function seek($position)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->seek($position));
    }

    /**
     * {@inheritDoc}
     */
    public function current()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->current());
    }

    /**
     * {@inheritDoc}
     */
    public function next()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->next());
    }

    /**
     * {@inheritDoc}
     */
    public function key()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->key());
    }

    /**
     * {@inheritDoc}
     */
    public function valid()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->valid());
    }

    /**
     * {@inheritDoc}
     */
    public function rewind()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->rewind());
    }

}