<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Observation

class Event implements \PHPCR\Observation\EventInterface
{
    /**
     * {@inheritDoc}
     */
    public function getType()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getType())
    }

    /**
     * {@inheritDoc}
     */
    public function getPath()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getPath())
    }

    /**
     * {@inheritDoc}
     */
    public function getUserID()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getUserID())
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentifier()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getIdentifier())
    }

    /**
     * {@inheritDoc}
     */
    public function getInfo()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getInfo())
    }

    /**
     * {@inheritDoc}
     */
    public function getUserData()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getUserData())
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDate())
    }

    /**
     * {@inheritDoc}
     */
    public function getPropertyType()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getPropertyType())
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimaryNodeType()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getPrimaryNodeType())
    }

    /**
     * {@inheritDoc}
     */
    public function getMixinNodeTypes()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getMixinNodeTypes())
    }

}