<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Observation

class EventListener implements \PHPCR\Observation\EventListenerInterface
{
    /**
     * {@inheritDoc}
     */
    public function onEvent(\Traversable $events)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->onEvent($events))
    }

}