<?php

// autogenerated: Wed, 10 Sep 2014 18:08:53 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Observation;


class Event implements \PHPCR\Observation\EventInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Observation\EventInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getType());
    }

    /**
     * {@inheritDoc}
     */
    public function getPath()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getPath());
    }

    /**
     * {@inheritDoc}
     */
    public function getUserID()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getUserID());
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentifier()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getIdentifier());
    }

    /**
     * {@inheritDoc}
     */
    public function getInfo()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getInfo());
    }

    /**
     * {@inheritDoc}
     */
    public function getUserData()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getUserData());
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getDate());
    }

    /**
     * {@inheritDoc}
     */
    public function getPropertyType()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getPropertyType());
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimaryNodeType()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getPrimaryNodeType());
    }

    /**
     * {@inheritDoc}
     */
    public function getMixinNodeTypes()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getMixinNodeTypes());
    }

}