<?php

// autogenerated: Wed, 10 Sep 2014 18:08:53 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Observation;


class EventFilter implements \PHPCR\Observation\EventFilterInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Observation\EventFilterInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

    /**
     * {@inheritDoc}
     */
    public function setEventTypes($eventTypes)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->setEventTypes($eventTypes));
    }

    /**
     * {@inheritDoc}
     */
    public function getEventTypes()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getEventTypes());
    }

    /**
     * {@inheritDoc}
     */
    public function setAbsPath($absPath)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->setAbsPath($absPath));
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsPath()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getAbsPath());
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDeep($isDeep)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->setIsDeep($isDeep));
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDeep()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getIsDeep());
    }

    /**
     * {@inheritDoc}
     */
    public function setIdentifiers(array $identifiers)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->setIdentifiers($identifiers));
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentifiers()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getIdentifiers());
    }

    /**
     * {@inheritDoc}
     */
    public function setNodeTypes(array $nodeTypes)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->setNodeTypes($nodeTypes));
    }

    /**
     * {@inheritDoc}
     */
    public function getNodeTypes()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getNodeTypes());
    }

    /**
     * {@inheritDoc}
     */
    public function setNoLocal($noLocal)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->setNoLocal($noLocal));
    }

    /**
     * {@inheritDoc}
     */
    public function getNoLocal()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getNoLocal());
    }

}