<?php

// autogenerated: Wed, 10 Sep 2014 13:41:16 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Observation;


class Event implements \PHPCR\Observation\EventInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Observation\EventInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getUserID());
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentifier()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getIdentifier());
    }

    /**
     * {@inheritDoc}
     */
    public function getInfo()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getInfo());
    }

    /**
     * {@inheritDoc}
     */
    public function getUserData()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getUserData());
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDate());
    }

    /**
     * {@inheritDoc}
     */
    public function getPropertyType()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getPropertyType());
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimaryNodeType()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getPrimaryNodeType());
    }

    /**
     * {@inheritDoc}
     */
    public function getMixinNodeTypes()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getMixinNodeTypes());
    }

}