<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Observation

class EventJournal implements \PHPCR\Observation\EventJournalInterface
{
    /**
     * {@inheritDoc}
     */
    public function skipTo($date)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->skipTo($date))
    }

}