<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Observation

class ObservationManager implements \PHPCR\Observation\ObservationManagerInterface
{
    /**
     * {@inheritDoc}
     */
    public function addEventListener(EventListenerInterface $listener, EventFilterInterface $filter)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->addEventListener($listener $filter))
    }

    /**
     * {@inheritDoc}
     */
    public function removeEventListener(EventListenerInterface $listener)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->removeEventListener($listener))
    }

    /**
     * {@inheritDoc}
     */
    public function getRegisteredEventListeners()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getRegisteredEventListeners())
    }

    /**
     * {@inheritDoc}
     */
    public function setUserData($userData)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setUserData($userData))
    }

    /**
     * {@inheritDoc}
     */
    public function getEventJournal(EventFilterInterface $filter)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getEventJournal($filter))
    }

    /**
     * {@inheritDoc}
     */
    public function createEventFilter()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->createEventFilter())
    }

}