<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Query\QOM

class BindVariableValue implements \PHPCR\Query\QOM\BindVariableValueInterface
{
    /**
     * {@inheritDoc}
     */
    public function getBindVariableName()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getBindVariableName())
    }

}