<?php

// autogenerated: Wed, 10 Sep 2014 18:08:53 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Query\QOM;


class ChildNodeJoinCondition implements \PHPCR\Query\QOM\ChildNodeJoinConditionInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Query\QOM\ChildNodeJoinConditionInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

    /**
     * {@inheritDoc}
     */
    public function getChildSelectorName()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getChildSelectorName());
    }

    /**
     * {@inheritDoc}
     */
    public function getParentSelectorName()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getParentSelectorName());
    }

}