<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Query\QOM

class DescendantNodeJoinCondition implements \PHPCR\Query\QOM\DescendantNodeJoinConditionInterface
{
    /**
     * {@inheritDoc}
     */
    public function getDescendantSelectorName()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDescendantSelectorName())
    }

    /**
     * {@inheritDoc}
     */
    public function getAncestorSelectorName()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getAncestorSelectorName())
    }

}