<?php

// autogenerated: Wed, 10 Sep 2014 18:08:53 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Query\QOM;


class DescendantNodeJoinCondition implements \PHPCR\Query\QOM\DescendantNodeJoinConditionInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Query\QOM\DescendantNodeJoinConditionInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

    /**
     * {@inheritDoc}
     */
    public function getDescendantSelectorName()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getDescendantSelectorName());
    }

    /**
     * {@inheritDoc}
     */
    public function getAncestorSelectorName()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getAncestorSelectorName());
    }

}