<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Query\QOM

class EquiJoinCondition implements \PHPCR\Query\QOM\EquiJoinConditionInterface
{
    /**
     * {@inheritDoc}
     */
    public function getSelector1Name()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getSelector1Name())
    }

    /**
     * {@inheritDoc}
     */
    public function getProperty1Name()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getProperty1Name())
    }

    /**
     * {@inheritDoc}
     */
    public function getSelector2Name()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getSelector2Name())
    }

    /**
     * {@inheritDoc}
     */
    public function getProperty2Name()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getProperty2Name())
    }

}