<?php

// autogenerated: Wed, 10 Sep 2014 13:41:17 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Query\QOM;


class EquiJoinCondition implements \PHPCR\Query\QOM\EquiJoinConditionInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Query\QOM\EquiJoinConditionInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getSelector2Name());
    }

    /**
     * {@inheritDoc}
     */
    public function getProperty2Name()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getProperty2Name());
    }

}