<?php

// autogenerated: Wed, 10 Sep 2014 18:08:53 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Query\QOM;


class Join implements \PHPCR\Query\QOM\JoinInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Query\QOM\JoinInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

    /**
     * {@inheritDoc}
     */
    public function getLeft()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getLeft());
    }

    /**
     * {@inheritDoc}
     */
    public function getRight()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getRight());
    }

    /**
     * {@inheritDoc}
     */
    public function getJoinType()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getJoinType());
    }

    /**
     * {@inheritDoc}
     */
    public function getJoinCondition()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getJoinCondition());
    }

}