<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Query\QOM

class Length implements \PHPCR\Query\QOM\LengthInterface
{
    /**
     * {@inheritDoc}
     */
    public function getPropertyValue()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getPropertyValue())
    }

}