<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Query\QOM

class Literal implements \PHPCR\Query\QOM\LiteralInterface
{
    /**
     * {@inheritDoc}
     */
    public function getLiteralValue()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getLiteralValue())
    }

}