<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Query\QOM

class Not implements \PHPCR\Query\QOM\NotInterface
{
    /**
     * {@inheritDoc}
     */
    public function getConstraint()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getConstraint())
    }

}