<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Query\QOM

class PropertyExistence implements \PHPCR\Query\QOM\PropertyExistenceInterface
{
    /**
     * {@inheritDoc}
     */
    public function getSelectorName()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getSelectorName())
    }

    /**
     * {@inheritDoc}
     */
    public function getPropertyName()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getPropertyName())
    }

}