<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Query\QOM

class QueryObjectModelConstants implements \PHPCR\Query\QOM\QueryObjectModelConstantsInterface
{
}