<?php

// autogenerated: Wed, 10 Sep 2014 18:08:53 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Query\QOM;


class SameNodeJoinCondition implements \PHPCR\Query\QOM\SameNodeJoinConditionInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\Query\QOM\SameNodeJoinConditionInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

    /**
     * {@inheritDoc}
     */
    public function getSelector1Name()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getSelector1Name());
    }

    /**
     * {@inheritDoc}
     */
    public function getSelector2Name()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getSelector2Name());
    }

    /**
     * {@inheritDoc}
     */
    public function getSelector2Path()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getSelector2Path());
    }

}