<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\Query\QOM

class SameNodeJoinCondition implements \PHPCR\Query\QOM\SameNodeJoinConditionInterface
{
    /**
     * {@inheritDoc}
     */
    public function getSelector1Name()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getSelector1Name())
    }

    /**
     * {@inheritDoc}
     */
    public function getSelector2Name()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getSelector2Name())
    }

    /**
     * {@inheritDoc}
     */
    public function getSelector2Path()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getSelector2Path())
    }

}