<?php

// autogenerated: Wed, 10 Sep 2014 13:41:17 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\NodeType;


class NodeDefinition implements \PHPCR\NodeType\NodeDefinitionInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\NodeType\NodeDefinitionInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDefaultPrimaryType());
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultPrimaryTypeName()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDefaultPrimaryTypeName());
    }

    /**
     * {@inheritDoc}
     */
    public function allowsSameNameSiblings()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->allowsSameNameSiblings());
    }

    /**
     * {@inheritDoc}
     */
    public function getDeclaringNodeType()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDeclaringNodeType());
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getName());
    }

    /**
     * {@inheritDoc}
     */
    public function isAutoCreated()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isAutoCreated());
    }

    /**
     * {@inheritDoc}
     */
    public function isMandatory()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isMandatory());
    }

    /**
     * {@inheritDoc}
     */
    public function getOnParentVersion()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getOnParentVersion());
    }

    /**
     * {@inheritDoc}
     */
    public function isProtected()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isProtected());
    }

}