<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\NodeType

class NodeType implements \PHPCR\NodeType\NodeTypeInterface
{
    /**
     * {@inheritDoc}
     */
    public function getSupertypes()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getSupertypes())
    }

    /**
     * {@inheritDoc}
     */
    public function getSupertypeNames()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getSupertypeNames())
    }

    /**
     * {@inheritDoc}
     */
    public function getDeclaredSupertypes()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDeclaredSupertypes())
    }

    /**
     * {@inheritDoc}
     */
    public function getSubtypes()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getSubtypes())
    }

    /**
     * {@inheritDoc}
     */
    public function getDeclaredSubtypes()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDeclaredSubtypes())
    }

    /**
     * {@inheritDoc}
     */
    public function isNodeType($nodeTypeName)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isNodeType($nodeTypeName))
    }

    /**
     * {@inheritDoc}
     */
    public function getPropertyDefinitions()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getPropertyDefinitions())
    }

    /**
     * {@inheritDoc}
     */
    public function getChildNodeDefinitions()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getChildNodeDefinitions())
    }

    /**
     * {@inheritDoc}
     */
    public function canSetProperty($propertyName, $value)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->canSetProperty($propertyName $value))
    }

    /**
     * {@inheritDoc}
     */
    public function canAddChildNode($childNodeName, $nodeTypeName = null)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->canAddChildNode($childNodeName $nodeTypeName))
    }

    /**
     * {@inheritDoc}
     */
    public function canRemoveNode($nodeName)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->canRemoveNode($nodeName))
    }

    /**
     * {@inheritDoc}
     */
    public function canRemoveProperty($propertyName)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->canRemoveProperty($propertyName))
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getName())
    }

    /**
     * {@inheritDoc}
     */
    public function getDeclaredSupertypeNames()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDeclaredSupertypeNames())
    }

    /**
     * {@inheritDoc}
     */
    public function isAbstract()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isAbstract())
    }

    /**
     * {@inheritDoc}
     */
    public function isMixin()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isMixin())
    }

    /**
     * {@inheritDoc}
     */
    public function hasOrderableChildNodes()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->hasOrderableChildNodes())
    }

    /**
     * {@inheritDoc}
     */
    public function isQueryable()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isQueryable())
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimaryItemName()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getPrimaryItemName())
    }

    /**
     * {@inheritDoc}
     */
    public function getDeclaredPropertyDefinitions()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDeclaredPropertyDefinitions())
    }

    /**
     * {@inheritDoc}
     */
    public function getDeclaredChildNodeDefinitions()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDeclaredChildNodeDefinitions())
    }

}