<?php

// autogenerated: Wed, 10 Sep 2014 13:41:17 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\NodeType;


class NodeTypeTemplate implements \PHPCR\NodeType\NodeTypeTemplateInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\NodeType\NodeTypeTemplateInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setAbstract($abstractStatus));
    }

    /**
     * {@inheritDoc}
     */
    public function setMixin($mixin)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setMixin($mixin));
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderableChildNodes($orderable)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setOrderableChildNodes($orderable));
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimaryItemName($name)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setPrimaryItemName($name));
    }

    /**
     * {@inheritDoc}
     */
    public function setQueryable($queryable)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setQueryable($queryable));
    }

    /**
     * {@inheritDoc}
     */
    public function getPropertyDefinitionTemplates()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getPropertyDefinitionTemplates());
    }

    /**
     * {@inheritDoc}
     */
    public function getNodeDefinitionTemplates()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getNodeDefinitionTemplates());
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getName());
    }

    /**
     * {@inheritDoc}
     */
    public function getDeclaredSupertypeNames()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDeclaredSupertypeNames());
    }

    /**
     * {@inheritDoc}
     */
    public function isAbstract()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isAbstract());
    }

    /**
     * {@inheritDoc}
     */
    public function isMixin()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isMixin());
    }

    /**
     * {@inheritDoc}
     */
    public function hasOrderableChildNodes()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->hasOrderableChildNodes());
    }

    /**
     * {@inheritDoc}
     */
    public function isQueryable()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isQueryable());
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimaryItemName()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getPrimaryItemName());
    }

    /**
     * {@inheritDoc}
     */
    public function getDeclaredPropertyDefinitions()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDeclaredPropertyDefinitions());
    }

    /**
     * {@inheritDoc}
     */
    public function getDeclaredChildNodeDefinitions()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDeclaredChildNodeDefinitions());
    }

}