<?php

// autogenerated: Wed, 10 Sep 2014 18:08:53 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\NodeType;


class NodeTypeDefinition implements \PHPCR\NodeType\NodeTypeDefinitionInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\NodeType\NodeTypeDefinitionInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getName());
    }

    /**
     * {@inheritDoc}
     */
    public function getDeclaredSupertypeNames()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getDeclaredSupertypeNames());
    }

    /**
     * {@inheritDoc}
     */
    public function isAbstract()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->isAbstract());
    }

    /**
     * {@inheritDoc}
     */
    public function isMixin()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->isMixin());
    }

    /**
     * {@inheritDoc}
     */
    public function hasOrderableChildNodes()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->hasOrderableChildNodes());
    }

    /**
     * {@inheritDoc}
     */
    public function isQueryable()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->isQueryable());
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimaryItemName()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getPrimaryItemName());
    }

    /**
     * {@inheritDoc}
     */
    public function getDeclaredPropertyDefinitions()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getDeclaredPropertyDefinitions());
    }

    /**
     * {@inheritDoc}
     */
    public function getDeclaredChildNodeDefinitions()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getDeclaredChildNodeDefinitions());
    }

}