<?php

// autogenerated: Wed, 10 Sep 2014 18:08:53 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\NodeType;


class NodeDefinition implements \PHPCR\NodeType\NodeDefinitionInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\NodeType\NodeDefinitionInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

    /**
     * {@inheritDoc}
     */
    public function getRequiredPrimaryTypes()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getRequiredPrimaryTypes());
    }

    /**
     * {@inheritDoc}
     */
    public function getRequiredPrimaryTypeNames()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getRequiredPrimaryTypeNames());
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultPrimaryType()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getDefaultPrimaryType());
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultPrimaryTypeName()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getDefaultPrimaryTypeName());
    }

    /**
     * {@inheritDoc}
     */
    public function allowsSameNameSiblings()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->allowsSameNameSiblings());
    }

    /**
     * {@inheritDoc}
     */
    public function getDeclaringNodeType()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getDeclaringNodeType());
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getName());
    }

    /**
     * {@inheritDoc}
     */
    public function isAutoCreated()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->isAutoCreated());
    }

    /**
     * {@inheritDoc}
     */
    public function isMandatory()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->isMandatory());
    }

    /**
     * {@inheritDoc}
     */
    public function getOnParentVersion()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getOnParentVersion());
    }

    /**
     * {@inheritDoc}
     */
    public function isProtected()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->isProtected());
    }

}