<?php

// autogenerated: Wed, 10 Sep 2014 18:08:53 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\NodeType;


class PropertyDefinitionTemplate implements \PHPCR\NodeType\PropertyDefinitionTemplateInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\NodeType\PropertyDefinitionTemplateInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->setName($name));
    }

    /**
     * {@inheritDoc}
     */
    public function setAutoCreated($autoCreated)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->setAutoCreated($autoCreated));
    }

    /**
     * {@inheritDoc}
     */
    public function setMandatory($mandatory)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->setMandatory($mandatory));
    }

    /**
     * {@inheritDoc}
     */
    public function setOnParentVersion($opv)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->setOnParentVersion($opv));
    }

    /**
     * {@inheritDoc}
     */
    public function setProtected($protectedStatus)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->setProtected($protectedStatus));
    }

    /**
     * {@inheritDoc}
     */
    public function setRequiredType($type)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->setRequiredType($type));
    }

    /**
     * {@inheritDoc}
     */
    public function setValueConstraints(array $constraints)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->setValueConstraints($constraints));
    }

    /**
     * {@inheritDoc}
     */
    public function setDefaultValues(array $defaultValues)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->setDefaultValues($defaultValues));
    }

    /**
     * {@inheritDoc}
     */
    public function setMultiple($multiple)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->setMultiple($multiple));
    }

    /**
     * {@inheritDoc}
     */
    public function setAvailableQueryOperators(array $operators)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->setAvailableQueryOperators($operators));
    }

    /**
     * {@inheritDoc}
     */
    public function setFullTextSearchable($fullTextSearchable)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->setFullTextSearchable($fullTextSearchable));
    }

    /**
     * {@inheritDoc}
     */
    public function setQueryOrderable($queryOrderable)
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->setQueryOrderable($queryOrderable));
    }

    /**
     * {@inheritDoc}
     */
    public function getRequiredType()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getRequiredType());
    }

    /**
     * {@inheritDoc}
     */
    public function getValueConstraints()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getValueConstraints());
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultValues()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getDefaultValues());
    }

    /**
     * {@inheritDoc}
     */
    public function isMultiple()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->isMultiple());
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailableQueryOperators()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getAvailableQueryOperators());
    }

    /**
     * {@inheritDoc}
     */
    public function isFullTextSearchable()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->isFullTextSearchable());
    }

    /**
     * {@inheritDoc}
     */
    public function isQueryOrderable()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->isQueryOrderable());
    }

    /**
     * {@inheritDoc}
     */
    public function getDeclaringNodeType()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getDeclaringNodeType());
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getName());
    }

    /**
     * {@inheritDoc}
     */
    public function isAutoCreated()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->isAutoCreated());
    }

    /**
     * {@inheritDoc}
     */
    public function isMandatory()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->isMandatory());
    }

    /**
     * {@inheritDoc}
     */
    public function getOnParentVersion()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getOnParentVersion());
    }

    /**
     * {@inheritDoc}
     */
    public function isProtected()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->isProtected());
    }

}