<?php

// autogenerated: Wed, 10 Sep 2014 18:08:53 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\NodeType;


class PropertyDefinition implements \PHPCR\NodeType\PropertyDefinitionInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\NodeType\PropertyDefinitionInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

    /**
     * {@inheritDoc}
     */
    public function getRequiredType()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getRequiredType());
    }

    /**
     * {@inheritDoc}
     */
    public function getValueConstraints()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getValueConstraints());
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultValues()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getDefaultValues());
    }

    /**
     * {@inheritDoc}
     */
    public function isMultiple()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->isMultiple());
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailableQueryOperators()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getAvailableQueryOperators());
    }

    /**
     * {@inheritDoc}
     */
    public function isFullTextSearchable()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->isFullTextSearchable());
    }

    /**
     * {@inheritDoc}
     */
    public function isQueryOrderable()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->isQueryOrderable());
    }

    /**
     * {@inheritDoc}
     */
    public function getDeclaringNodeType()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getDeclaringNodeType());
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getName());
    }

    /**
     * {@inheritDoc}
     */
    public function isAutoCreated()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->isAutoCreated());
    }

    /**
     * {@inheritDoc}
     */
    public function isMandatory()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->isMandatory());
    }

    /**
     * {@inheritDoc}
     */
    public function getOnParentVersion()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->getOnParentVersion());
    }

    /**
     * {@inheritDoc}
     */
    public function isProtected()
    {
        return $this->decoratorFactory->decorate(__METHOD__, $this->component->isProtected());
    }

}