<?php

// autogenerated: Wed, 10 Sep 2014 09:56:22 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\NodeType

class PropertyDefinition implements \PHPCR\NodeType\PropertyDefinitionInterface
{
    /**
     * {@inheritDoc}
     */
    public function getRequiredType()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getRequiredType())
    }

    /**
     * {@inheritDoc}
     */
    public function getValueConstraints()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getValueConstraints())
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultValues()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDefaultValues())
    }

    /**
     * {@inheritDoc}
     */
    public function isMultiple()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isMultiple())
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailableQueryOperators()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getAvailableQueryOperators())
    }

    /**
     * {@inheritDoc}
     */
    public function isFullTextSearchable()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isFullTextSearchable())
    }

    /**
     * {@inheritDoc}
     */
    public function isQueryOrderable()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isQueryOrderable())
    }

    /**
     * {@inheritDoc}
     */
    public function getDeclaringNodeType()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDeclaringNodeType())
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getName())
    }

    /**
     * {@inheritDoc}
     */
    public function isAutoCreated()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isAutoCreated())
    }

    /**
     * {@inheritDoc}
     */
    public function isMandatory()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isMandatory())
    }

    /**
     * {@inheritDoc}
     */
    public function getOnParentVersion()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getOnParentVersion())
    }

    /**
     * {@inheritDoc}
     */
    public function isProtected()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isProtected())
    }

}