<?php

// autogenerated: Wed, 10 Sep 2014 13:41:17 +0200

namespace Sulu\Component\PhpcrDecorator\PHPCR\NodeType;


class PropertyDefinitionTemplate implements \PHPCR\NodeType\PropertyDefinitionTemplateInterface
{
    protected $component;
    protected $decoratorFactory;

    public function __construct(
        \PHPCR\NodeType\PropertyDefinitionTemplateInterface $component,
        \Sulu\Component\PhpcrDecorator\DecoratorFactoryInterface $decoratorFactory
    )
    {
        $this->component = $component;
        $this->decoratorFactory = $decoratorFactory;
    }

        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setMandatory($mandatory));
    }

    /**
     * {@inheritDoc}
     */
    public function setOnParentVersion($opv)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setOnParentVersion($opv));
    }

    /**
     * {@inheritDoc}
     */
    public function setProtected($protectedStatus)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setProtected($protectedStatus));
    }

    /**
     * {@inheritDoc}
     */
    public function setRequiredType($type)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setRequiredType($type));
    }

    /**
     * {@inheritDoc}
     */
    public function setValueConstraints(array $constraints)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setValueConstraints($constraints));
    }

    /**
     * {@inheritDoc}
     */
    public function setDefaultValues(array $defaultValues)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setDefaultValues($defaultValues));
    }

    /**
     * {@inheritDoc}
     */
    public function setMultiple($multiple)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setMultiple($multiple));
    }

    /**
     * {@inheritDoc}
     */
    public function setAvailableQueryOperators(array $operators)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setAvailableQueryOperators($operators));
    }

    /**
     * {@inheritDoc}
     */
    public function setFullTextSearchable($fullTextSearchable)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setFullTextSearchable($fullTextSearchable));
    }

    /**
     * {@inheritDoc}
     */
    public function setQueryOrderable($queryOrderable)
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->setQueryOrderable($queryOrderable));
    }

    /**
     * {@inheritDoc}
     */
    public function getRequiredType()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getRequiredType());
    }

    /**
     * {@inheritDoc}
     */
    public function getValueConstraints()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getValueConstraints());
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultValues()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDefaultValues());
    }

    /**
     * {@inheritDoc}
     */
    public function isMultiple()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isMultiple());
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailableQueryOperators()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getAvailableQueryOperators());
    }

    /**
     * {@inheritDoc}
     */
    public function isFullTextSearchable()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isFullTextSearchable());
    }

    /**
     * {@inheritDoc}
     */
    public function isQueryOrderable()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isQueryOrderable());
    }

    /**
     * {@inheritDoc}
     */
    public function getDeclaringNodeType()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getDeclaringNodeType());
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getName());
    }

    /**
     * {@inheritDoc}
     */
    public function isAutoCreated()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isAutoCreated());
    }

    /**
     * {@inheritDoc}
     */
    public function isMandatory()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isMandatory());
    }

    /**
     * {@inheritDoc}
     */
    public function getOnParentVersion()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->getOnParentVersion());
    }

    /**
     * {@inheritDoc}
     */
    public function isProtected()
    {
        return $this->getDecorator()->decorate(__METHOD__, $this->__component()->isProtected());
    }

}